### ISSUE TITLE
Microsoft MVP API

### ISSUE THREAD

**Issue by johnnliu** [microsoft/PowerPlatformConnectors#28] opened 2019-05-17 18:08 UTC
**Describe the bug**

I have a custom connector for Microsoft MVP API.
https://github.com/johnnliu/flow/blob/master/MVP%20Production.swagger.json 

The API needs two pieces of authentication.

MSA and a per-user Ocp-Apim-Subscription-Key.

I'm not sure how to write a custom connector that has two authentication parts.  Also, the API header is needed in every call.

Would love to pull it into this project, but there's an issue with it and I'm not sure how to write this swagger.  Right now, people that used this had to take a copy and override line 35.

**Comment by schabungbam** [comment] 2019-05-31 18:58
Hi John,

For the API header, you can make it work in one of 3 ways:

(1) Define the header in the swagger for every operation.  This will mean the end user provide the info in every API call.
(2) Use the "Set header" policy in your connector, and use a hard-code a static value there.  Works well if you plan to deploy the connector for a limited environment and you dont want to bother the end user to provide this value.
(3) Add a connection paremter, and then use the "Set header" policy to stamp the header picking the value from the connection parameter.  See the Azure Key Vault example for how to use a connection parameter.

You can also do (1) and (2) by making the header parameter.  That way, if the key is not provided a default will be used.  One of the customers I spoke to yesterday used that approach.

It will be great if you can submit your custom connector as a sample.

**Comment by garrytrinder** [comment] 2019-06-01 11:26
@johnnliu sounds similar to how the Harvest API works, I used option 1 suggested by @schabungbam in my connector as the Harvest API requires the Harvest Account Id with every request.

![image](https://user-images.githubusercontent.com/11563347/58747821-5e981080-8468-11e9-8560-9dc9ef88edb0.png)

https://github.com/garrytrinder/harvest-api-powerplatform-custom-connector/blob/master/Harvest-API.swagger.json

**Comment by mamurshe** [comment] 2019-09-20 22:26
Closing this since @garrytrinder @schabungbam posted some suggestion. Please reopen if the issue isn't resolved.

**Closed by mamurshe** 2019-09-20 22:26 UTC
