### ISSUE TITLE
Swagger error using Facebook connector

### ISSUE THREAD

**Issue by Okafawa** [microsoft/PowerPlatformConnectors#254] opened 2020-05-12 15:04 UTC
**Describe the bug**
When using the Facebook connector, I get a swagger error.

**To Reproduce**
-Create a Facebook custom  connector on Power Automate.
-Import the apiDefinition.Swagger.json
-Create the connector

**Expected behavior**
The connector is expected to be created successfully

**Environment summary**

**Additional context**
**Error message:**
_Specified swagger has the following errors: 'Error : paths/~1{pageId}~1feed/get/parameters/0/x-ms-dynamic-values/parameters/Accept : The parameter could not be found in operation 'GetMyPages' in the swagger document.
   ##   Error : paths/~1{pageId}~1feed/post/parameters/0/x-ms-dynamic-values/parameters/Accept : The parameter could not be found in operation 'GetMyPages' in the swagger document.__

**Comment by e21vconci** [comment] 2020-11-03 18:03
same bug

**Comment by mamurshe** [comment] 2021-08-05 17:11
Duplicate of https://github.com/microsoft/PowerPlatformConnectors/issues/790

**Closed by mamurshe** 2021-08-05 17:11 UTC
Labels: bug, connector
